name: Node Cache
description: Caches Node and PNPM binaries

runs:
  using: composite
  steps:
    - name: Get Node.js and PNPM versions
      id: tooling-versions
      shell: bash
      run: |
        mvn help:evaluate -Dexpression=node.version
        echo "node=$(mvn help:evaluate -Dexpression=node.version -q -DforceStdout | cut -c 2-)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: cache-nodejs
      name: Cache Node.js
      with:
        path: |
          ~/.m2/repository/com/github/eirslett/node
        key: nodejs-${{ steps.tooling-versions.outputs.node }}
        enableCrossOsArchive: true

    - name: Download Node.js
      if: steps.cache-nodejs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
        cd ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
        curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz
        curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-win-x64.zip https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-win-x64.zip
