name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Get Node.js version
        id: tooling-versions
        shell: bash
        run: |
          echo "node=$(mvn help:evaluate -Dexpression=node.version -q -DforceStdout | cut -c 2-)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache-nodejs
        name: Cache Node.js
        with:
          path: |
            ~/.m2/repository/com/github/eirslett/node
          key: nodejs-${{ steps.tooling-versions.outputs.node }}

      - name: Download Node.js
        if: steps.cache-nodejs.cache-hit != 'true'
        run: |
          mkdir -p ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
          cd ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
          curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz
          curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-win-x64.zip https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-win-x64.zip

  test:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - uses: actions/cache@v4
        id: cache-nodejs
        name: Cache Node.js
        with:
          path: |
            ~/.m2/repository/com/github/eirslett/node
          key: nodejs-${{ steps.tooling-versions.outputs.node }}

      - name: Download Node.js
        if: steps.cache-nodejs.cache-hit != 'true'
        run: |
          mkdir -p ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
          cd ~/.m2/repository/com/github/eirslett/node/${{ steps.tooling-versions.outputs.node }}
          curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-linux-x64.tar.gz
          curl --retry 3 --retry-delay 30 -q -o node-${{ steps.tooling-versions.outputs.node }}-win-x64.zip https://nodejs.org/dist/v${{ steps.tooling-versions.outputs.node }}/node-v${{ steps.tooling-versions.outputs.node }}-win-x64.zip


      - run: mvn -X install